### PR TITLE
Added Foundation SASS

### PR DESCRIPTION
**Pull request by rasummer**

### CODE REVIEW

**Comment by huntc** [comment]
If we are now using sass then do we still need less etc?

Also can you not just pull in the web jar for foundation and overly its styles?  Lower maintenance ...

**Comment by rasummer** [comment]
Yes, we can pull LESS out, I will do so.

I want to be able to conditionally compile parts of the Foundation library and change settings etc. Can we do this from the web jar folder?

**Comment by rasummer** [comment]
looks like I had already pulled LESS out of the plugins.sbt

**Comment by huntc** [comment]
How about stylus (can't look at mo - out and about)

**Comment by huntc** [comment]
> I want to be able to conditionally compile parts of the Foundation library and change settings etc. Can do this from the web jar folder?

Can you import a sass file and override?

**Comment by rasummer** [comment]
I was using stylus for the other styles, although there aren't too many so I could convert those over to sass and have everything compile into one stylesheet.

**Comment by rasummer** [comment]
That is essentially what we are doing. We have the entire foundation SASS sources in the assets folder. I turn on the styles I want by uncommenting certain includes. I'm also uncommenting certain settings in order to override the defaults. This is the preferred way of doing it. I don't touch the original SASS files so that upgrades remain easy, but I get the power of compiling down only the parts I need now. In the future we may use more of the library. The way it's set up now is perfect for my use.

**Comment by rasummer** [comment]
Can you import a sass file and override?

Oh... I assume you are suggesting I import the sass files from the webjar... correct?

**Comment by huntc** [comment]
Yes indeedy.

**Comment by huntc** [comment]
Closing this out as I'm forking the repo over onto typesafehub. Please re-create the PR over there.

**Pull request closed without merging**
